GET https://google-meet-api.us.auth0.com/userinfo HTTP/1.1
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkpnU2REOVZwSmhPVVBXUmxWTGlxUCJ9.eyJpc3MiOiJodHRwczovL2Rldi04MjcxczExdS51cy5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTA2NjkyMDI5NTU5NzgyNDE0NjAiLCJhdWQiOlsiaHR0cHM6Ly9nb29nbGUtbWVldC1hcGkuY29tIiwiaHR0cHM6Ly9kZXYtODI3MXMxMXUudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY2Mjg2OTI3NywiZXhwIjoxNjYyOTU1Njc3LCJhenAiOiJwcTQ1bDhnRVZsMnNTN05DdmFnUDVSY0U2NENRQmE3USIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwifQ.jv2HOKq3OcTrUiMQ8CXb9noKLCEoMTyiFPN4Gc0-4kjySyJ5QC8Ce8QLaSY5lVgdgMMZFXhnFtE5rgEazqHV8va_lUedz7ZeG1Qq-xP3F8hGOuIR2FTvuRROYxTBp2lvn1qUkZ6jZi3CDXOhYbHpfjFTk0o82iJBWjQe4OhbrBO0vwxr93rdm8XYZ_pUdNZ2c0XPQWYNp6ZVCFEhZDPjO_DJXChaSuhBgzpwFPotQd9QAhYrvrB7x6vF6t2wIX4HpmVrRiKZ06qnLYrssEghiCFrNSLh71aL4u8PM7kMUUazNuYDpwCGba5kF3UYt8gTVFA14GXcBHQaXcMp33501g